//
//  Disclaimer.swift
//  PPLIR-FRAT
//
//  Created by Patrick de Nonneville on 01/03/2021.
//

import Foundation
import SwiftUI

struct DisclaimerView : View {
    
    @AppStorage("firstTime") var firstTime: Bool = true
    
    var body: some View {
        VStack {
            VStack {
                HStack {
                    Image("55")
                    Text("Flight Risk Assesment Tool").font(Font.headline)
                }
                Text("Disclaimer").font(Font.largeTitle)
            }
            Spacer()
            ScrollView(.vertical, showsIndicators: true) {
                VStack {
                    Text("BASIS ON WHICH WE MAKE THIS TOOL AVAILABLE TO YOU AND DISCLAIMER.").font(Font.footnote)
                    Text("")
                    Text("THIS APPLICATION IS PROVIDED, FOR FREE, AS A TRAINING TOOL TO HELP MEMBERS OF PPL/IR EUROPE CONSIDER SOME OF THE RISKS INHERENT IN GENERAL AVIATION FLYING. THE RISK SCORE THAT THE TOOL GENERATES, THE RISK FACTORS THAT IT TAKES INTO ACCOUNT, AND THE WEIGHTINGS THAT IT ASSIGNS TO EACH FACTOR ARE INTENDED ONLY AS AN AID TO DISCUSSION AND CONSIDERATION OF RISK; THEY ARE NOT THE PRODUCT OF ANY SCIENTIFIC RESEARCH, THEY HAVE NOT BEEN INDEPENDENTLY VALIDATED, AND THEY DO NOT CLAIM TO BE AUTHORITATIVE. THEY MUST NOT BE MISTAKEN FOR ADVICE. FURTHER, AS WITH ALL SOFTWARE, THIS APPLICATION MAY CONTAIN BUGS AND MAY PRESENT A RISK SCORE THAT DOES NOT CORRESPOND TO THE INPUTS.").font(Font.footnote)
                    Text("")
                    Text("USE OF THIS TOOL DOES NOT IN ANY WAY, SHAPE OR FORM RELIEVE YOU OF ANY RESPONSIBILITY LINKED TO THE PLANNING AND CONDUCT OF A POTENTIAL FLIGHT. YOU ARE NOT PERMITTED TO USE THIS TOOL AS A SUBSTITUTE FOR ANY PRE-FLIGHT PLANNING STEP THAT YOU WOULD TAKE IF THIS TOOL WERE NOT AVAILABLE; AND YOU ARE NOT PERMITTED TO RELY ON ANY RISK SCORE GENERATED BY THIS APPLICATION AS THE BASIS (OR AS ANY PART OF THE BASIS) OF A DECISION TO UNDERTAKE ANY FLIGHT.").font(Font.footnote)
                    Text("")
                    Text("THIS APPLICATION IS PROVIDED “AS IS” WITHOUT ANY WARRANTY, REPRESENTATION, OR CONDITION OF ANY KIND; AND ANY WARRANTY, EXPRESS OR IMPLIED IS EXCLUDED AND DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY LAW, INCLUDING THE WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE.").font(Font.footnote)
                    Text("")
                }
                VStack{
                    Text("TO THE EXTENT PERMITTED BY LAW:PPL/IR EUROPE LTD, ITS OFFICERS AND MEMBERS, AND THE CREATORS AND DEVELOPERS OF THIS APPLICATION DISCLAIM ANY AND ALL RESPONSIBILITY FOR THE CONSEQUENCES OF USING THIS APPLICATION; AND IN NO EVENT SHALL PPL/IR EUROPE LTD, ITS OFFICERS AND MEMBERS, AND/OR THE CREATORS AND DEVELOPERS OF THIS APPLICATION BE LIABLE FOR ANY DAMAGE WHATSOEVER, INCLUDING SPECIAL, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES, INCLUDING LOST PROFIT (WHETHER DIRECT OR INDIRECT), ARISING OUT OF OR CONNECTED WITH ANY OF THE MATERIAL OR THE USE, RELIANCE UPON OR PERFORMANCE OF ANY MATERIAL CONTAINED IN THIS TOOL.").font(Font.footnote)
                    Text("")
                    Text("THE PILOT IN COMMAND IS SOLELY RESPONSIBLE FOR THE SAFE, PROPER AND LEGAL OPERATION OF HIS/HER AIRCRAFT").font(Font.footnote)
                    Text("")
                    Spacer()
                    Button("Accept", action: toContent)
                }
            }
            .padding()
            
        }
    }
    
    func toContent() {
//        firstTime = false
        if let window = UIApplication.shared.windows.first {
                window.rootViewController = UIHostingController(rootView: ContentView())
                window.makeKeyAndVisible()
            }
    }
    
}



struct DisclaimerView_Previews: PreviewProvider {
    static var previews: some View {
        DisclaimerView().environment(\.colorScheme, .light)
    }
}
